version: '3.8'

services:
  api-reservas:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python app.py
    environment:
      FLASK_DEBUG: 1
    restart: unless-stopped
